
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ShoppingCart, Search, Plus, Calendar, DollarSign, TrendingUp, Users, Edit, Printer, Trash2, Banknote, CreditCard, Smartphone } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { BatteryTypeSelector } from "@/components/BatteryTypeSelector";
import { PurchaseItem } from "@/types/purchases";
import { useEffect, useState } from "react"; 
import { supabase } from "@/integrations/supabase/client";
import { usePurchases } from "@/hooks/usePurchases";
import { Purchase as ServicePurchase, PurchaseFormData } from "@/services/purchaseService";

const paymentMethodMap: Record<string, "cash" | "card" | "bank_transfer" | "check"> = {
  "نقداً": "cash",
  "بطاقة": "card", 
  "تحويل": "bank_transfer",
  "آجل": "check"
};

const statusMap: Record<string, "pending" | "completed" | "cancelled"> = {
  "قيد الانتظار": "pending",
  "مكتملة": "completed",
  "ملغاة": "cancelled"
};

const PurchasesPage = () => {
  const { purchases, isLoading, createPurchase, updatePurchase, deletePurchase, isCreating, isUpdating, isDeleting } = usePurchases();
  const [searchTerm, setSearchTerm] = useState("");
  const [showSupplierDialog, setShowSupplierDialog] = useState(false);
  const [editingPurchase, setEditingPurchase] = useState<ServicePurchase | null>(null);
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [newPurchase, setNewPurchase] = useState({
    date: new Date().toISOString().split('T')[0],
    supplierId: "",
    supplierName: "",
    items: [] as PurchaseItem[],
    discount: 0,
    paymentMethod: "آجل"
  });

  const [selectedSupplier, setSelectedSupplier] = useState<{
    id: string;
    name: string;
    balance: number;
    total_purchases: number;
    total_amount: number;
  } | null>(null);

  const filteredPurchases = purchases.filter((purchase: ServicePurchase) =>
    purchase.invoice_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (purchase.suppliers?.name || '').toLowerCase().includes(searchTerm.toLowerCase())
  );
 
  const handleSupplierSelect = (supplier: { id: string; name: string; balance: number; total_purchases: number; total_amount: number }) => {
    setSelectedSupplier(supplier);
    setNewPurchase(prev => ({
      ...prev,
      supplierId: supplier.id,
      supplierName: supplier.name
    }));
    setShowSupplierDialog(false);
  };

  const calculateTotals = () => {
    const subtotal = newPurchase.items.reduce((sum, item) => sum + item.total, 0);
    const discountAmount = (subtotal * newPurchase.discount) / 100;
    const afterDiscount = subtotal - discountAmount;
    const tax = afterDiscount * 0.15; // ضريبة القيمة المضافة 15%
    const total = afterDiscount + tax;

    return { subtotal, discountAmount, tax, total };
  };

  const fetchBatteryTypeId = async (batteryTypeName: string): Promise<string | null> => {
    const { data, error } = await supabase
      .from("battery_types")
      .select("id")
      .eq("name", batteryTypeName)
      .single();

    if (error) {
      console.error("خطأ أثناء جلب معرف نوع البطارية:", error);
      return null;
    }

    return data?.id || null;
  };

  const handleSavePurchase = async () => {
    try {
      console.log("بدء عملية حفظ الفاتورة...");
  
      if (!selectedSupplier || newPurchase.items.length === 0) {
        console.error("خطأ: لم يتم اختيار المورد أو إضافة أصناف.");
        toast({
          title: "خطأ",
          description: "يرجى اختيار مورد وإضافة أصناف",
          variant: "destructive"
        });
        return;
      }
  
      const { subtotal, tax, total } = calculateTotals();
      
      // Convert items to the format expected by purchaseService
      const itemsForService = await Promise.all(
        newPurchase.items.map(async (item) => {
          const batteryTypeId = await fetchBatteryTypeId(item.batteryType);
          if (!batteryTypeId) {
            throw new Error(`نوع البطارية "${item.batteryType}" غير موجود`);
          }
          
          return {
            battery_type_id: batteryTypeId,
            quantity: item.quantity,
            price_per_kg: item.price,
            total: item.total
          };
        })
      );

      const purchaseData: PurchaseFormData = {
        invoice_number: "", // Will be generated by service
        date: newPurchase.date,
        supplier_id: newPurchase.supplierId,
        subtotal,
        discount: newPurchase.discount,
        tax,
        total,
        payment_method: paymentMethodMap[newPurchase.paymentMethod] ?? "cash",
        status: "completed",
        items: itemsForService
      };

      console.log("بيانات الفاتورة للإرسال:", purchaseData);

      await createPurchase(purchaseData);

      // Reset form
      setNewPurchase({
        date: new Date().toISOString().split('T')[0],
        supplierId: "",
        supplierName: "",
        items: [],
        discount: 0,
        paymentMethod: "آجل"
      });
      setSelectedSupplier(null);

    } catch (err: any) {
      console.error("خطأ غير متوقع:", err);
      toast({
        title: "خطأ",
        description: err.message || "حدث خطأ غير متوقع أثناء حفظ الفاتورة",
        variant: "destructive"
      });
    }
  };

  const handleEditPurchase = (purchase: ServicePurchase) => {
    setEditingPurchase(purchase);
    setShowEditDialog(true);
  };

  const handlePrintPurchase = (purchase: ServicePurchase) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>فاتورة مشتريات - ${purchase.invoice_number}</title>
          <style>
            body { font-family: 'Tajawal', Arial, sans-serif; direction: rtl; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .details { margin: 20px 0; }
            .items-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            .items-table th, .items-table td { border: 1px solid #ddd; padding: 8px; text-align: right; }
            .items-table th { background-color: #f5f5f5; }
            .totals { margin-top: 20px; text-align: right; }
            .total-line { display: flex; justify-content: space-between; margin: 5px 0; }
            .final-total { font-size: 18px; font-weight: bold; border-top: 2px solid #333; padding-top: 10px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>فاتورة مشتريات</h1>
            <h2>رقم الفاتورة: ${purchase.invoice_number}</h2>
          </div>
          
          <div class="details">
            <p><strong>التاريخ:</strong> ${purchase.date}</p>
            <p><strong>المورد:</strong> ${purchase.suppliers?.name || 'غير معروف'}</p>
            <p><strong>طريقة الدفع:</strong> ${purchase.payment_method}</p>
          </div>
          
          <table class="items-table">
            <thead>
              <tr>
                <th>نوع البطارية</th>
                <th>الكمية</th>
                <th>السعر</th>
                <th>المجموع</th>
              </tr>
            </thead>
            <tbody>
              ${(purchase.items || purchase.purchase_items || []).map((item: any) => `
                <tr>
                  <td>${item.batteryType || 'غير معروف'}</td>
                  <td>${item.quantity}</td>
                  <td>${(item.price || item.price_per_kg || 0).toFixed(2)} ريال</td>
                  <td>${item.total.toFixed(2)} ريال</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          
          <div class="totals">
            <div class="total-line">
              <span>المجموع الفرعي:</span>
              <span>${purchase.subtotal.toFixed(2)} ريال</span>
            </div>
            <div class="total-line">
              <span>الخصم:</span>
              <span>${((purchase.subtotal * purchase.discount) / 100).toFixed(2)} ريال</span>
            </div>
            <div class="total-line">
              <span>الضريبة (15%):</span>
              <span>${purchase.tax.toFixed(2)} ريال</span>
            </div>
            <div class="total-line final-total">
              <span>المجموع النهائي:</span>
              <span>${purchase.total.toFixed(2)} ريال</span>
            </div>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
  };
 
  const handleDeletePurchase = async (purchase: ServicePurchase) => {
    try {
      await deletePurchase(purchase.id);
    } catch (err: any) {
      console.error("خطأ في حذف الفاتورة:", err.message);
    }
  };

  const fetchSuppliers = async () => {
    const { data, error } = await supabase
      .from("suppliers")
      .select("id, name, balance, total_purchases, total_amount");

    if (error) {
      console.error("Error fetching suppliers:", error);
      return [];
    }

    return data;
  };

  const totals = calculateTotals();

  const LocalSupplierSearchDialog = ({ open, onClose, onSupplierSelect }: { 
    open: boolean; 
    onClose: () => void; 
    onSupplierSelect: (supplier: { id: string; name: string; balance: number; total_purchases: number; total_amount: number }) => void 
  }) => {
    const [searchTerm, setSearchTerm] = useState("");
    const [suppliers, setSuppliers] = useState<{ id: string; name: string; balance: number; total_purchases: number; total_amount: number }[]>([]);
  
    useEffect(() => {
      fetchSuppliers().then(setSuppliers);
    }, []);
  
    const filteredSuppliers = suppliers.filter(supplier =>
      supplier.name.toLowerCase().includes(searchTerm.toLowerCase())
    );
  
    return (
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-md" dir="rtl">
          <DialogHeader>
            <DialogTitle style={{ fontFamily: 'Tajawal, sans-serif' }}>
              اختيار المورد
            </DialogTitle>
          </DialogHeader>
  
          <div className="space-y-4">
            <div className="relative">
              <Search className="absolute right-3 top-3 h-4 w-4 text-gray-400" />
              <Input
                placeholder="ابحث عن مورد..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pr-10"
                style={{ fontFamily: 'Tajawal, sans-serif' }}
              />
            </div>
  
            <div className="max-h-60 overflow-y-auto space-y-2">
              {filteredSuppliers.map(supplier => (
                <div
                  key={supplier.id}
                  onClick={() => {
                    onSupplierSelect(supplier);
                    setSearchTerm("");
                    onClose();
                  }}
                  className="p-3 border rounded cursor-pointer hover:bg-gray-50"
                >
                  <div className="flex justify-between items-center">
                    <div>
                      <p className="font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                        {supplier.name}
                      </p>
                    </div>
                    <div className="text-left">
                      <p className={`font-bold ${supplier.balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                        {supplier.balance.toLocaleString()} ريال
                      </p>
                      <p className="text-xs text-gray-500">الرصيد</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </DialogContent>
      </Dialog>
    );
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-lg" style={{ fontFamily: 'Tajawal, sans-serif' }}>
          جاري التحميل...
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="shadow-lg">
        <CardHeader className="bg-[#eff6ff] text-gray-600">
          <div className="flex justify-center">
            <CardTitle className="flex items-center gap-2 flex-row-reverse text-lg sm:text-xl" style={{ fontFamily: 'Tajawal, sans-serif' }}>
              إدارة المشتريات
              <ShoppingCart className="w-4 h-4 sm:w-5 sm:h-5" />
            </CardTitle>
          </div>
        </CardHeader>

        <CardContent className="p-4 sm:p-6">
          {/* Add New Purchase Form */}
          <div className="bg-gray-50 p-4 rounded-lg mb-6">
            <h3 className="text-lg font-semibold mb-4" style={{ fontFamily: 'Tajawal, sans-serif' }}>
              إضافة فاتورة مشتريات جديدة
            </h3>

            <div className="flex flex-col md:flex-row gap-4 mb-4 items-end">
              {/* تاريخ الفاتورة */}
              <div className="flex-4">
                <Label htmlFor="date" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                  التاريخ
                </Label>
                <Input
                  type="date"
                  id="date"
                  value={newPurchase.date}
                  onChange={(e) => setNewPurchase({ ...newPurchase, date: e.target.value })}
                />
              </div>

              {/* اختيار المورد */}
              <div className="flex-1 flex flex-col">
                <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>
                  اختر المورد
                </Label>
                <div className="flex items-center gap-2 mt-1">
                  <Button
                    variant="outline"
                    onClick={() => setShowSupplierDialog(true)}
                    className="flex-1 flex items-center justify-between"
                    style={{ fontFamily: 'Tajawal, sans-serif' }}
                  >
                    <span>
                      {selectedSupplier ? selectedSupplier.name : "اختر المورد"}
                    </span>
                    <Search className="w-4 h-4" />
                  </Button>
                  {selectedSupplier && (
                    <span
                      className={`text-sm font-bold whitespace-nowrap ${selectedSupplier.balance >= 0
                        ? "text-green-600 bg-green-100 py-2 px-6 rounded"
                        : "text-red-600 bg-red-100 py-2 px-6 rounded"
                        }`}
                    >
                      الرصيد: {selectedSupplier.balance.toLocaleString()} ريال
                    </span>
                  )}
                </div>
              </div>
            </div>

            {/* Add Items */}
            <div>
              <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>أصناف الفاتورة</Label>
              <div className="space-y-3 mt-2">
                {newPurchase.items.map((item, index) => (
                  <div key={item.id} className="grid grid-cols-12 gap-2 items-end">
                    <div className="col-span-4">
                      <BatteryTypeSelector
                        value={item.batteryType}
                        onChange={(value) => {
                          const updatedItems = [...newPurchase.items];
                          updatedItems[index].batteryType = value;
                          setNewPurchase({ ...newPurchase, items: updatedItems });
                        }}
                        placeholder="اختر نوع البطارية"
                      />
                    </div>
                    <div className="col-span-2">
                      <Input
                        type="number"
                        placeholder="الكمية"
                        value={item.quantity || ''}
                        onChange={(e) => {
                          const updatedItems = [...newPurchase.items];
                          updatedItems[index].quantity = Number(e.target.value) || 0;
                          updatedItems[index].total = updatedItems[index].quantity * updatedItems[index].price;
                          setNewPurchase({ ...newPurchase, items: updatedItems });
                        }}
                      />
                    </div>
                    <div className="col-span-2">
                      <Input
                        type="number"
                        placeholder="السعر"
                        value={item.price || ''}
                        onChange={(e) => {
                          const updatedItems = [...newPurchase.items];
                          updatedItems[index].price = Number(e.target.value) || 0;
                          updatedItems[index].total = updatedItems[index].quantity * updatedItems[index].price;
                          setNewPurchase({ ...newPurchase, items: updatedItems });
                        }}
                      />
                    </div>
                    <div className="col-span-2">
                      <Input
                        value={item.total.toLocaleString()}
                        disabled
                        className="bg-gray-100"
                      />
                    </div>
                    <div className="col-span-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          const updatedItems = newPurchase.items.filter((_, i) => i !== index);
                          setNewPurchase({ ...newPurchase, items: updatedItems });
                        }}
                        disabled={newPurchase.items.length === 1}
                      >
                        حذف
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
              <Button
                onClick={() => {
                  const newItem: PurchaseItem = {
                    id: Date.now().toString(),
                    batteryType: "",
                    quantity: 0,
                    price: 0,
                    total: 0,
                  };
                  setNewPurchase({ ...newPurchase, items: [...newPurchase.items, newItem] });
                }}
                variant="outline"
                className="mt-3 w-full flex items-center gap-2"
                style={{ fontFamily: 'Tajawal, sans-serif' }}
              >
                <Plus className="w-4 h-4" />
                إضافة صنف
              </Button>
            </div>

            <div>
              <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>طريقة الدفع</Label>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-2">
                  {[
                    { value: "نقداً", label: "نقداً", icon: DollarSign },
                    { value: "بطاقة", label: "بطاقة", icon: CreditCard },
                    { value: "تحويل", label: "تحويل", icon: Banknote },
                    { value: "آجل", label: "آجل", icon: Smartphone }
                  ].map(method => {
                    const Icon = method.icon;
                    return (
                      <Button
                        key={method.value}
                        variant={newPurchase.paymentMethod === method.value ? "default" : "outline"}
                        onClick={() => setNewPurchase({ ...newPurchase, paymentMethod: method.value })}
                        className="flex items-center gap-2"
                        style={{ fontFamily: 'Tajawal, sans-serif' }}
                      >
                        <Icon className="w-4 h-4" />
                        {method.label}
                      </Button>
                    );
                  })}
                </div>
            </div>

          </div>

          <Card>
            <CardHeader>
              <CardTitle style={{ fontFamily: 'Tajawal, sans-serif' }}>
                ملخص الفاتورة
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between">
                <span style={{ fontFamily: 'Tajawal, sans-serif' }}>المجموع الفرعي:</span>
                <span className="font-bold">{totals.subtotal.toLocaleString()} ريال</span>
              </div>
              <div className="flex justify-between">
                <span style={{ fontFamily: 'Tajawal, sans-serif' }}>الخصم:</span>
                <span className="font-bold text-red-600">-{totals.discountAmount.toLocaleString()} ريال</span>
              </div>
              <div className="flex justify-between">
                <span style={{ fontFamily: 'Tajawal, sans-serif' }}>ضريبة القيمة المضافة (15%):</span>
                <span className="font-bold">{totals.tax.toLocaleString()} ريال</span>
              </div>
              <div className="border-t pt-4">
                <div className="flex justify-between text-lg">
                  <span className="font-bold" style={{ fontFamily: 'Tajawal, sans-serif' }}>الإجمالي:</span>
                  <span className="font-bold text-green-600">{totals.total.toLocaleString()} ريال</span>
                </div>
              </div>
              {newPurchase.paymentMethod === 'آجل' && (
                <div className="bg-yellow-50 p-3 rounded border">
                  <p className="text-sm text-yellow-800" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                    ملاحظة: سيتم إضافة هذا المبلغ لرصيد المورد في حالة الشراء الآجل
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          <div className="flex gap-2 ">
            <Button
              onClick={handleSavePurchase}
              disabled={isCreating}
              className="flex-1 bg-green-600"
              style={{ fontFamily: 'Tajawal, sans-serif' }}
            >
              {isCreating ? "جاري الحفظ..." : "إنشاء الفاتورة"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Purchases List */}
      <Card>
        {/* Statistics */}
        <div className="grid grid-cols-1 sm:grid-cols-3 px-5 py-5 gap-4 mb-6">
          <Card>
            <CardContent className="p-4 text-center">
              <ShoppingCart className="w-8 h-8 mx-auto mb-2 text-green-600" />
              <p className="text-2xl font-bold">{purchases.length}</p>
              <p className="text-sm text-gray-600" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                إجمالي المشتريات
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4 text-center">
              <img src="/assets/icons/SaudiRG.svg" alt="Custom Icon" className="w-8 h-8 mx-auto mb-2" />
              <p className="text-2xl font-bold">
                {purchases.reduce((sum, p) => sum + p.total, 0).toFixed(2)}
              </p>
              <p className="text-sm text-gray-600" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                إجمالي القيمة
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4 text-center">
              <TrendingUp className="w-8 h-8 mx-auto mb-2 text-purple-600" />
              <p className="text-2xl font-bold">
                {purchases.reduce((sum, p) => sum + p.tax, 0).toFixed(2)}
              </p>
              <p className="text-sm text-gray-600" style={{ fontFamily: 'Tajawal, sans-serif' }}>
                إجمالي الضريبة
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="mb-6 px-5">
          <div className="relative">
            <Search className="absolute right-3 top-3 h-4 w-4 text-gray-400" />
            <Input
              placeholder="ابحث عن فاتورة مشتريات..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pr-10 text-sm"
              style={{ fontFamily: 'Tajawal, sans-serif' }}
            />
          </div>
        </div>

        <CardHeader>
          <CardTitle style={{ fontFamily: 'Tajawal, sans-serif' }}>قائمة المشتريات</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>رقم الفاتورة</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>التاريخ</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>المورد</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>المجموع</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>طريقة الدفع</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>الحالة</th>
                  <th className="p-3 text-right font-semibold" style={{ fontFamily: 'Tajawal, sans-serif' }}>الإجراءات</th>
                </tr>
              </thead>
              <tbody>
                {filteredPurchases.map((purchase) => (
                  <tr key={purchase.id} className="border-b hover:bg-gray-50">
                    <td className="p-3 font-semibold">{purchase.invoice_number}</td>
                    <td className="p-3">{purchase.date}</td>
                    <td className="p-3" style={{ fontFamily: 'Tajawal, sans-serif' }}>{purchase.suppliers?.name || 'غير معروف'}</td>
                    <td className="p-3 font-bold text-green-600">{purchase.total.toFixed(2)} ريال</td>
                    <td className="p-3">
                      <Badge variant={purchase.payment_method === "check" ? "secondary" : "default"}>{purchase.payment_method}</Badge>
                    </td>
                    <td className="p-3">
                      <Badge variant="default">{purchase.status}</Badge>
                    </td>
                    <td className="p-3">
                      <div className="flex gap-1">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleEditPurchase(purchase)}
                          disabled={isUpdating}
                        >
                          <Edit className="w-3 h-3" />
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handlePrintPurchase(purchase)}
                        >
                          <Printer className="w-3 h-3" />
                        </Button>
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => handleDeletePurchase(purchase)}
                          disabled={isDeleting}
                        >
                          <Trash2 className="w-3 h-3" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <LocalSupplierSearchDialog
        open={showSupplierDialog}
        onClose={() => setShowSupplierDialog(false)}
        onSupplierSelect={handleSupplierSelect}
      />

      {/* Edit Purchase Dialog */}
      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent className="max-w-2xl" dir="rtl">
          <DialogHeader>
            <DialogTitle style={{ fontFamily: 'Tajawal, sans-serif' }}>
              تعديل فاتورة المشتريات - {editingPurchase?.invoice_number}
            </DialogTitle>
          </DialogHeader>
          {editingPurchase && (
            <EditPurchaseForm
              purchase={editingPurchase}
              onSave={(updatedPurchase) => {
                setShowEditDialog(false);
                // The hook will handle the update automatically
              }}
              onCancel={() => setShowEditDialog(false)}
            />
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};

// EditPurchaseForm component definition
type EditPurchaseFormProps = {
  purchase: ServicePurchase;
  onSave: (updatedPurchase: ServicePurchase) => void;
  onCancel: () => void;
};

const EditPurchaseForm = ({ purchase, onSave, onCancel }: EditPurchaseFormProps) => {
  const { updatePurchase } = usePurchases();
  const [editedPurchase, setEditedPurchase] = useState<ServicePurchase>({ ...purchase });

  const handleItemChange = (index: number, field: keyof PurchaseItem, value: any) => {
    const updatedItems = [...(editedPurchase.items || editedPurchase.purchase_items || [])];
    updatedItems[index] = {
      ...updatedItems[index],
      [field]: value,
      total:
        field === "quantity" || field === "price_per_kg"
          ? (field === "quantity" ? value : updatedItems[index].quantity) *
          (field === "price_per_kg" ? value : updatedItems[index].price_per_kg)
          : updatedItems[index].total,
    };
    setEditedPurchase({ ...editedPurchase, items: updatedItems });
  };

  const handleRemoveItem = (index: number) => {
    const updatedItems = (editedPurchase.items || editedPurchase.purchase_items || []).filter((_: any, i: number) => i !== index);
    setEditedPurchase({ ...editedPurchase, items: updatedItems });
  };

  const handleSave = async () => {
    try {
      const items = editedPurchase.items || editedPurchase.purchase_items || [];
      const subtotal = items.reduce((sum: number, item: any) => sum + item.total, 0);
      const discountAmount = (subtotal * editedPurchase.discount) / 100;
      const afterDiscount = subtotal - discountAmount;
      const tax = afterDiscount * 0.15;
      const total = afterDiscount + tax;

      const updateData = {
        date: editedPurchase.date,
        subtotal,
        discount: editedPurchase.discount,
        tax,
        total,
        payment_method: editedPurchase.payment_method,
        status: editedPurchase.status,
        items: items.map((item: any) => ({
          battery_type_id: item.battery_type_id,
          quantity: item.quantity,
          price_per_kg: item.price_per_kg || item.price,
          total: item.total
        }))
      };

      await updatePurchase({ id: editedPurchase.id, data: updateData });
      onSave(editedPurchase);
    } catch (err: any) {
      console.error("خطأ غير متوقع:", err.message);
      toast({
        title: "خطأ",
        description: err.message || "حدث خطأ غير متوقع أثناء تعديل الفاتورة",
        variant: "destructive",
      });
    }
  };
 
  return (
    <div className="space-y-4">
      <div className="flex flex-col md:flex-row gap-4 mb-4 items-end">
        <div className="flex-4">
          <Label htmlFor="date" style={{ fontFamily: 'Tajawal, sans-serif' }}>
            التاريخ
          </Label>
          <Input
            type="date"
            id="date"
            value={editedPurchase.date}
            onChange={(e) => setEditedPurchase({ ...editedPurchase, date: e.target.value })}
          />
        </div>
        <div className="flex-1 flex flex-col">
          <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>
            اسم المورد
          </Label>
          <Input
            value={editedPurchase.suppliers?.name || 'غير معروف'}
            disabled
            style={{ fontFamily: 'Tajawal, sans-serif' }}
          />
        </div>
      </div>
      <div>
        <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>أصناف الفاتورة</Label>
        <div className="space-y-3 mt-2">
          {(editedPurchase.items || editedPurchase.purchase_items || []).map((item: any, index: number) => (
            <div key={item.id || index} className="grid grid-cols-12 gap-2 items-end">
              <div className="col-span-4">
                <Input
                  value={item.batteryType || 'غير معروف'}
                  disabled
                  style={{ fontFamily: 'Tajawal, sans-serif' }}
                />
              </div>
              <div className="col-span-2">
                <Input
                  type="number"
                  placeholder="الكمية"
                  value={item.quantity || ''}
                  onChange={(e) => handleItemChange(index, "quantity", Number(e.target.value) || 0)}
                />
              </div>
              <div className="col-span-2">
                <Input
                  type="number"
                  placeholder="السعر"
                  value={item.price_per_kg || ''}
                  onChange={(e) => handleItemChange(index, "price", Number(e.target.value) || 0)}
                />
              </div>
              <div className="col-span-2">
                <Input
                  value={item.total?.toLocaleString() || '0'}
                  disabled
                  className="bg-gray-100"
                />
              </div>
              <div className="col-span-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleRemoveItem(index)}
                  disabled={(editedPurchase.items || editedPurchase.purchase_items || []).length === 1}
                >
                  حذف
                </Button>
              </div>
            </div>
          ))}
        </div>
      </div>
      <div>
        <Label style={{ fontFamily: 'Tajawal, sans-serif' }}>الخصم (%)</Label>
        <Input
          type="number"
          value={editedPurchase.discount}
          onChange={(e) => setEditedPurchase({ ...editedPurchase, discount: Number(e.target.value) || 0 })}
        />
      </div>
      <div className="flex gap-2 justify-end">
        <Button variant="outline" onClick={onCancel}>
          إلغاء
        </Button>
        <Button onClick={handleSave} className="bg-green-600">
          حفظ التعديلات
        </Button>
      </div>
    </div>
  );
};

export default PurchasesPage;
