// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znqexctvtnlqbzxrxfxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucWV4Y3R2dG5scWJ6eHJ4ZnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjE0MTIsImV4cCI6MjA2NTEzNzQxMn0.X9W5Vlx2r3VW4LJT5MoraNRVe2u-oCZhjyD8VKkrF_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);